### ISSUE TITLE
CaaSMapper | [XMLParser]: Error parsing XML whenever & is supplied

### ISSUE THREAD

**Issue by samo4b** [e-Spirit/javascript-content-api-library#189]
We get an error whenever we try to add an `&` inside a CMS_INPUT_DOM element.
The text is just a plain text without any styling:

![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/e50a8d4d-a4bc-47d5-8dd8-d615286865ac)

However in the Frontend we get the following error:
```
CaaSMapper | [XMLParser]: Error parsing XML | {} | <div data-fs-style="format.plain">Nach diesem Satz kommt en kaufmännisches Und & mit Text danach</div> 
```

We do use this in the Frontend:
```
<FSXARichText
    v-for="(message, index) in messages"
    :key="index"
    :content="message.content"
    :data="message.data"
    :type="message.type"
/>
```

And inside the individual components extended by FSXABaseRichTextElement we simply use `<render-content />`  with a bit of styling:

![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/caa56e50-4fdb-4fc5-95c0-e2ae9b70cf13)

This leads to the problem that everything from the & til the end is missing in the Frontend:
![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/cb636281-1915-4e72-a7b4-f940cdc7e8f6)

Reference to the API (where this very likely goes wrong):
[XMLParser.ts#55](https://github.com/e-Spirit/javascript-content-api-library/blob/c8dae095bccebc3dc53dce40087efc408d50e5ef/src/modules/XMLParser.ts#L55)

I suspect that the escaping with ENTITIES is not correctly applied but that is just my guess.
Please have a look at it.

**Comment by neo-reply-lukas** [comment]
I just double checked and i cannot reproduce this problem on my side with the latest version. What Version of fsxa-api do you use?
You can check what Version is actually used with ```npm list fsxa-api```

**Comment by jodeleit-es** [comment]
![image](https://github.com/e-Spirit/javascript-content-api-library/assets/95370962/8a1125fc-f01d-4986-b64d-a8d690680e06)

**Comment by samo4b** [comment]
@neo-reply-lukas We are using the latest versions:
```
"fsxa-api": "10.18.0",
"fsxa-nuxt-module": "npm:@neo-reply/fsxa-nuxt-module@8.0.0",
"fsxa-pattern-library": "npm:@neo-reply/fsxa-pattern-library@9.1.0",
```
@jodeleit-es I'll try that out and see if that helps us.

**Comment by samo4b** [comment]
@jodeleit-es We don't have any "CaaS" Conversion on our side (but something we could try out).

![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/af548d9f-c196-4d3d-826a-a7689c35084f)

Does this conversion really apply to the data which is then available in the CaaS?

**Comment by jodeleit-es** [comment]
> Does this conversion really apply to the data which is then available in the CaaS?

Yes

**Comment by samo4b** [comment]
@jodeleit-es Ok thanks I'll let the rule get set up and if that works for us I can close the ticket.

**Comment by samo4b** [comment]
@jodeleit-es Thank you for the hint it worked out great!
It solved every issue we had with & and the FSXARichText.

Just as an example:
![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/87289bd3-1e4f-4ce6-88e7-269d3f7f3b23)

Result in the Frontend:
![image](https://github.com/e-Spirit/javascript-content-api-library/assets/49033570/0f28322e-2aee-4f6a-b8bf-aa272b2ee69d)
