### ISSUE TITLE
fetchNavigation doesn't return all urls 

### ISSUE THREAD

**Issue by LarsOlt** [e-Spirit/javascript-content-api-library#200]
We have url paths that are generated from table entries by FS. 
https://docs.e-spirit.com/odfs/advanced-topics/generation/advanced-urls/index.html

The slug is generated from the title of the blog post.

Example: /blog/[slug] -> /blog/hello-world-post
https://www.gruenewoche.de/de/blog/mori-kocht-und-moderiert.html

When using the caas api these routes are missing in the response. Only one slug url from thousands exists.
We have already tried changing settings in the FS Site Architect.

<img width="420" alt="image" src="https://github.com/e-Spirit/javascript-content-api-library/assets/32353679/f82d72a6-572c-4575-9a96-83379c0bc2ca">

**Comment by nico-mcalley** [comment]
Hi Lars!
Thank you for reporting the problem.

The content API is using the CaaS and Navigation Service APIs in the background.
When the data is incorrect there, it will be wrong when using the content API as well.

Could you verify, the data is correct in Navigation Service?
The URL to test this should look similar to this:
https://<customer name>-navigationservice.e-spirit.cloud/navigation/release.<project UUID>?language=de_DE

When it turns out, that the problem is in fact somewhere in between Navigation Service and FirstSpirit, please open a ticket for our customer support. If the data in Navigation Service is correct, we need a reproduction setup for the potential bug. 

kind regards
Nico

**Comment by LarsOlt** [comment]
> Hi Lars! Thank you for reporting the problem.
> 
> The content API is using the CaaS and Navigation Service APIs in the background. When the data is incorrect there, it will be wrong when using the content API as well.
> 
> Could you verify, the data is correct in Navigation Service? The URL to test this should look similar to this: https://${customer-name}-navigationservice.e-spirit.cloud/navigation/release.${project UUID}?language=de_DE
> 
> When it turns out, that the problem is in fact somewhere in between Navigation Service and FirstSpirit, please open a ticket for our customer support. If the data in Navigation Service is correct, we need a reproduction setup for the potential bug.
> 
> kind regards Nico

Same result on the API, we will create a ticket

**Comment by jodeleit-es** [comment]
Maybe our initial interpretation of your ticket was wrong. 
Did you read [this part of the Navigation Service documentation](https://docs.e-spirit.com/module/navigation-service-fsm/Navigation_Service_FSM_Documentation_EN.html#content-projections)?

**Comment by jodeleit-es** [comment]
And this may also help: https://docs.e-spirit.com/module/caas-connect/CaaS_Connect_FSM_Documentation_EN.html#caas-json-format

**Comment by nico-mcalley** [comment]
When you want to implement an application, that does routing over a [FS content projection](https://docs.e-spirit.com/odfs/templates-basic/composition-tem/database-schema/dataset-output/index.html#content_projektion)  you could also have a look at our reference PWA implementation. 
https://github.com/e-Spirit/crownpeak-pwa-template/blob/8870a68877e1df3a25ab936387682ed8420decde/pages/%5B...slug%5D.vue#L52

**Comment by neo-reply-lukas** [comment]
Generally i would recommend not using NavigationService to resolve routes from ContentProjections, as the RegExp may lead to non deterministic behavior.
Instead, fetch routing info from CaaS With a filter equivalent to
_route = "PATH" or routes.route = "PATH"_

That may return either 
1 PageRef --> Not a Content Projection
1 Dataset --> Content Projection. PageRef Id in routes.pageRef
1 Dataset & 1 PageRef  --> Content Projection. PageRef Id in routes.pageRef is the same that was fetched

From that info, you know the context of your routing and may fetch the correct navigation by Locale and id of the pageRef referenced in the Dataset

**Comment by LarsOlt** [comment]
Thanks everyone! 
I built a query using `{"route":{"$regex":"/de/blog/*"}}` which returns all the matching datasets. 

Is it correct behavior that the navigation endpoint only returns one of the dynamic routes?
Is it possible to get all the dynamic routes from the navigation endpoint without a custom query?
